//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final
{
    using System;
    using System.Collections.Generic;
    
    public partial class job_details
    {
        public int id { get; set; }
        public string job_ttl { get; set; }
        public string work_location { get; set; }
        public Nullable<int> yrs_in_job { get; set; }
    }
}
