//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public int id { get; set; }
        public string first_nm { get; set; }
        public string last_nm { get; set; }
        public Nullable<System.DateTime> dtm { get; set; }
        public Nullable<int> chg_uid { get; set; }
        public Nullable<System.DateTime> chg_dtm { get; set; }
        public string stat_cd { get; set; }
    }
}
